# This is a basic workflow that is manually triggered

name: Deploy to Tsen

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HHmm
        utcOffset: "+01:00"
    - name: Use current time
      env:
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      run: echo $F_TIME

#      - name: Get current date
#        id: date
#        run: echo "MY_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
#      - name: Test the produced date
#        run: echo Current Date ${{ env.MY_DATE }} ${{ secrets.BAYERN_DOCKER_HUB }}/nordeck-dev/jitsi-meet:v0.4_${{ env.MY_DATE }}
           
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
       ref: nic/feat/general

# this step will get the commit id
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
      
#      - name: Setup Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
 
#      - name: Install NPM packages
#        run: npm install
        
 
#      - name: Make all
#        run: make all
 
#      - name: Make source-package
#        run: make source-package
 
#      - name: Login to Bayern DockerHub
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ secrets.BAYERN_DOCKER_HUB }}
#          username: ${{ secrets.BAYERN_DOCKERHUB_USERNAME }}
#          password: ${{ secrets.BAYERN_DOCKERHUB_TOKEN }}
 
#      - name: Build Docker Image
#        run: docker build . -t ${{ secrets.BAYERN_DOCKER_HUB }}/nordeck-dev/jitsi-meet:v0.4_${{ env.MY_DATE }}_${{ steps.vars.outputs.sha_short }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
 
 
#      - name: Build Docker Push
#        run: docker push  ${{ secrets.BAYERN_DOCKER_HUB }}/nordeck-dev/jitsi-meet:v0.4_${{ env.MY_DATE }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }} 
