# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


jobs:

  release:

    runs-on: ubuntu-latest

    steps:
        
      - name: Get current date
        id: date
        uses: 1466587594/get-current-time@v2
        with:
          format: YYYYMMDD-HHMM
          utcOffset: "+01:00"
          
        
        
      - name: Test the produced date
        run: echo Current Date ${{ steps.date.outputs.time }} ${{ secrets.BAYERN_DOCKER_HUB }}/nordeck-dev/jitsi-meet:v0.4_${{ steps.date.outputs.time }}
           
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
         ref: nic/feat/general

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
 
      - name: Install NPM packages
        run: npm install
        
 
      - name: Make all
        run: make all
 
      - name: Make source-package
        run: make source-package
 
      - name: Login to Bayern DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.BAYERN_DOCKER_HUB }}
          username: ${{ secrets.BAYERN_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BAYERN_DOCKERHUB_TOKEN }}
 
      - name: Build Docker Image
        run: docker build . -t ${{ secrets.BAYERN_DOCKER_HUB }}/nordeck-dev/jitsi-meet:v0.4_${{steps.date.outputs.time}}
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
 
 
      - name: Build Docker Push
        run: docker push  ${{ secrets.BAYERN_DOCKER_HUB }}/nordeck-dev/jitsi-meet:v0.4_${{ steps.date.outputs.time}}
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }} 
